### ISSUE TITLE
Kubernetes config doesn't work anymore on azure

### ISSUE THREAD

**Issue by cedrox** [Azure-Samples/multicontainerwordpress#4]
Hello, 
Redis container seem to fail to load on kubernetes config on azure website.
**Docker error** 
2019-04-12 12:11:48.466 ERROR - Container create failed for ******__a4f9_redis_0 with System.AggregateException, One or more errors occurred.
InnerException: Docker.DotNet.DockerApiException, Docker API responded with status code=BadRequest, response={"message":"conflicting options: dns and the network mode"}

Can you confirm ?
Thanks

**Comment by mgrabarz** [comment]
Same issue here with all yamls I tried, including official samples.

**Comment by msangapu-msft** [comment]
@yiliaomsft For awareness.

**Comment by msangapu-msft** [comment]
Followed-up internally.

#please-close

**Comment by waltherg** [comment]
@msangapu-msft have you found a fix for this yet? I am getting the same issue with multi-container kubernetes yamls of my own.

**Comment by msangapu-msft** [comment]
Hi team, we've removed Kubernetes configuration support based on customer feedback. For Kubernetes customers, we recommend Azure Kubernetes Service (AKS). 

Hope that helps!

**Comment by waltherg** [comment]
@msangapu-msft thanks for your response.

What customer feedback did you base your decision on to keep the Kubernetes tab in the app service container configuration section - thus forcing me to waste my time attempting to get a feature to work that has been discontinued?

![image](https://user-images.githubusercontent.com/3273502/61547793-6168b800-aa4c-11e9-81b9-4ba60412d09c.png)

Further, why do you keep outdated and confusing promotional material online promoting a feature that doesn't exist anymore?

https://azure.microsoft.com/de-de/updates/app-service-multi-container-and-linux-support-for-ase-preview/

![image](https://user-images.githubusercontent.com/3273502/61547910-a5f45380-aa4c-11e9-9880-816447cd8aa0.png)

**Comment by msangapu-msft** [comment]
@waltherg Sorry for the trouble. Yes, this was announced "in preview" last year. Since then, due to the low adoption rate, engineering decided to stop supporting it. We recommend using AKS on Azure. "In preview" features are known to change and this was one of those cases. Hope that helps. 

This is a Github sample repo and not the appropriate place to voice your concerns. If you have additional feedback, please voice it here: https://feedback.azure.com/ so it's viewed by the appropriate people.
